{{- if .Values.storage.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ required "storage.className is required" .Values.storage.className }}
  labels:
    {{- include "fss-kafka.labels" . | nindent 4 }}
provisioner: {{ required "storage.provisioner is required when storage.create=true" .Values.storage.provisioner }}
volumeBindingMode: {{ .Values.storage.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storage.allowVolumeExpansion }}
reclaimPolicy: {{ .Values.storage.reclaimPolicy }}
{{- with .Values.storage.parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
